# Generated by Django 4.0.4 on 2022-05-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
